[default]
author = "Johannes"
description = ""
email = "johannes-programming@mailfence.com"
github = "johannes-programming"
requires_python = "current"
v = "bump(2, 1)"
year = "current"

[general]
root = ""
